language: python
python:
  - "3.5"
# command to install dependencies
env:
    -DEBUG=True DATABASE_URL="postgres:trisha@localhost/youtube_database"
before_script:
  - psql -c 'create database youtube_database;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
# command to run tests
script:
  - python -m unittest discover tests
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: youtube-data-monitor
  on:
    branch: master
